### ISSUE TITLE
Oque falta?

### ISSUE THREAD

**Issue by ViniciusCarli** [Edwardpg/Mondinho#30]
### **Prioridades**
-Refatorar Visual - @GabrielBevilacqua @Edwardpg @ViniciusCarli
-Criar Tabela Vendedores e linkar com o banco de dados de vendas 
-Mask e Validação de CPF @Edwardpg 

Finalizadas
-Arrumar Login🎷 - @ViniciusCarli
-Nomes 🎷 - @GabrielBevilacqua  
-Colocar Métodos corretos no Data Module/Conexão 🎷 - @GabrielBevilacqua 
-Criação de um Data Module para cada Cds 🎷 - @Edwardpg 

### **Afazeres**
Finalizadas
-Tabela Usuários Cadastrados ✔️ - @Edwardpg 
-Controle De Usuário ✔️ - @GabrielBevilacqua 
-Impedir de se criar 2 usuários com o mesmo nome - @ViniciusCarli
-Logout ✔️ - @ViniciusCarli
-Relatório ✔️ - @Edwardpg 
-Atualizar data Atrasada em "Real Time" ✔️ - @ViniciusCarli
-Botão para Adiar Tarefa ✔️ - @ViniciusCarli 
-Trocar Componentes nos Status's para ComboBox ✔️ - @ViniciusCarli

**Comment by luizcastrolfc** [comment]
🌮 🔔

**Comment by erikunha** [comment]
:naoentendi: isso aqui 🌮
